In [2]:
import pandas as pd
import statsmodels.api as sm
df = pd.read_csv('data/processed/master_data.csv')
df

,Year,avg_sugar_price,diversion_pct,sugar_production_lmt,global_price_inr_per_quintal,Unnamed: 5,Unnamed: 6
0,2021.0,3550.125594,8.2,358.0,2883.504000,NaN,NaN
1,2022.0,3716.708543,10.4,328.2,3202.868500,NaN,NaN
2,2023.0,3864.484392,5.0,323.0,4266.220000,NaN,NaN
3,2024.0,4094.782713,11.7,264.0,3765.465000,NaN,NaN
4,2025.0,4165.209754,9.9,309.5,3245.704250,NaN,NaN
5,2026.0,4648.601053,9.9,306.0,3126.741346,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.dropna(how='all', inplace=True)
df = df.drop(columns=['Unnamed: 5','Unnamed: 6'])

df

,Year,avg_sugar_price,diversion_pct,sugar_production_lmt,global_price_inr_per_quintal
0,2021.0,3550.125594,8.2,358.0,2883.504000
1,2022.0,3716.708543,10.4,328.2,3202.868500
2,2023.0,3864.484392,5.0,323.0,4266.220000
3,2024.0,4094.782713,11.7,264.0,3765.465000
4,2025.0,4165.209754,9.9,309.5,3245.704250
5,2026.0,4648.601053,9.9,306.0,3126.741346

In [ ]:
df_train = df[df['Year'] <= 2025]

target = 'avg_sugar_price'
predictors = ['diversion_pct', 'sugar_production_lmt', 'global_price_inr_per_quintal']

X_train = sm.add_constant(df_train[predictors])
y_train = df_train[target]
model_train = sm.OLS(y_train, X_train).fit()

row_2026 = df[df['Year'] == 2026]
X_2026 = sm.add_constant(row_2026[predictors], has_constant='add')

predicted_2026 = model_train.predict(X_2026).values[0]
actual_2026 = row_2026[target].values[0]

print(f"Predicted 2026 price: {predicted_2026:.2f}")
print(f"Actual 2026 price: {actual_2026:.2f}")
print(f"Gap: {actual_2026 - predicted_2026:.2f} ({(actual_2026-predicted_2026)/actual_2026*100:.1f}%)")

Predicted 2026 price: 4147.28
Actual 2026 price: 4648.60
Gap: 501.32 (10.8%)